### PR TITLE
Expo 52 React Native 0.76 Support (0.4.0 release candidate)

### LINKED ISSUE #47: Config plugin fails with Expo SDK 52
Expo prebuild fails with following error:
```
Error: [ios.dangerous]: withIosDangerousBaseMod: Failed to match "/installer.target_installation_results.pod_target_installation_results/" in contents:
$VCEnableLocation=false
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

# @generated begin rn-video-set-rnvideousevideocaching - expo prebuild (DO NOT MODIFY) sync-6d1501be1513e0d61f29dc83e33eb880c8206459
$RNVideoUseVideoCaching = true
# @generated end rn-video-set-rnvideousevideocaching
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'PartifulDev' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
```

That's probably because `@expo/config-plugins` doesn't match the version of the package required by latest Expo SDK.

Bumping `expo-modules-core` to `2.0.1` will be probably required as well.

Are you going to update the library in following weeks?

### PR DESCRIPTION
**Pull request by nathan-ahn**
Adds support for Expo 52 and React Native 0.76. Non-backwards compatible. Fixes #47.

### CODE REVIEW

File: plugin/src/withPodfile.ts [hunk 1]
```diff
@@ -20,41 +19,47 @@ export const withPodfile: ConfigPlugin<{
...
-        newSrc: appClipTarget,
-        anchor: "Pod::UI.warn e",
-        offset: 3,
-        comment: "#",
-      }).contents;
+      // It's generally safer to use `mergeContents` to insert new content into the Podfile, but this new target should always be inserted at the end of the file.
+      podfileContent = podfileContent
+        .concat(`\n\n# >>> Inserted by react-native-app-clip\n`)
+        .concat(appClipTarget)
+        .concat(`\n\n# <<< Inserted by react-native-app-clip\n`);
```
Comment (kowczarz) [inline plugin/src/withPodfile.ts:62]: Why did you get rid of `mergeContents`?

File: tsconfig.json [hunk 2]
```diff
@@ -5,5 +5,5 @@
     "outDir": "./build"
   },
   "include": ["./src"],
-  "exclude": ["**/__mocks__/*", "**/__tests__/*"]
+  "exclude": ["**/__mocks__/*", "**/__tests__/*", "**/__rsc_tests__/*"]
```
Comment (kowczarz) [inline tsconfig.json:8]: Not sure if that change is necessary.

Comment (nathan-ahn) [reply tsconfig.json:8]: It was auto-added after upgrading the packages. I assumed it's a part of boilerplate, but considering some of the Expo packages don't include this I'll remove here.

File: plugin/src/withPodfile.ts (hunk 1 above)
Comment (nathan-ahn) [reply plugin/src/withPodfile.ts:62]: The previous `anchor` (`Pod::UI.warn e) was removed in Expo 52 and honestly was quite arbitrary. I believe it was chosen just because it happened to be the last identifiable line in the `Podfile`. Inserting at the end is much safer and resilient to future `Podfile` changes, especially when considering interactions with other plugins.

File: tsconfig.json (hunk 2 above)
Comment (nathan-ahn) [reply tsconfig.json:8]: This file was regenerated by `expo-module-scripts` after the upgrade and matches corresponding `tsconfig.json`'s of `expo-image-picker` and `expo-media-library`. I don't know the exact purpose of `/__rsc_tests__/`, but I trust the judgement of `expo-module-scripts` with regards to its exclusion.

**Comment by ailtonvivaz** [comment]
As Expo 52 and RN 0.76 requires iOS 15.1+, I think is a good idea update de default `deploymentTarget`
